### 1) GET - products
GET http://localhost:8080/api/v1/products
Accept: application/json

### 2) GET - produkt po id
GET http://localhost:8080/api/v1/products/33
Accept: application/json

### 3) DELETE - usuń produkt
DELETE http://localhost:8080/api/v1/products/6

### 4) POST - dodanie nowego produktu
POST http://localhost:8080/api/v1/products
Content-Type: application/json

{
  "quantity": 10,
  "name": "ProduktKurtka",
  "category": "CLOTHING",
  "price": 159.99
}

### 5) PUT - zaktualizuj nowy produkt
PUT http://localhost:8080/api/v1/products/33
Content-Type: application/json

{
  "quantity": 16,
  "name": "ProduktKurtka",
  "category": "CLOTHING",
  "price": 120.00
}

### 6) GET - wyświetl historię zmian produktu
GET http://localhost:8080/api/v1/products/33/history
Accept: application/json

### 7) GET - wyświetl listę forbidden phrases
GET http://localhost:8080/api/v1/forbidden-phrases
Accept: application/json

### 8) POST - próba dodania produktu o nazwie zabronionej
POST http://localhost:8080/api/v1/products
Content-Type: application/json

{
  "quantity": 5,
  "name": "FreeGadget",
  "category": "ELECTRONICS",
  "price": 199.99
}

### 9) POST - dodanie frazy zabronionej
POST http://localhost:8080/api/v1/forbidden-phrases
Content-Type: application/json

{
  "phrase": "forbidden"
}

### 10) DELETE - usunięcie frazy zabronionej
DELETE http://localhost:8080/api/v1/forbidden-phrases/20
